[package]
name = "paxos"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
tokio-serde-bincode = "0.2"
tokio-async-await = "0.1"
